services:
  mq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:management
    restart: always
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
    volumes:
      - data:/var/lib/rabbitmq

volumes:
  data:
